fail_fast: true
exclude: '^(scripts|notebooks).*$'
repos:
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.340
    hooks:
    - id: pyright
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: jupytext-pair-notebooks
        name: jupytext-pair-notebooks
        entry: jupytext --set-formats ipynb,py:percent
        files: notebooks/\.ipynb
        stages: [commit]
        language: python
        additional_dependencies:
          - jupytext==1.14.4
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        args: [-s, --typeguard-packages, tests, --log-cli-level=debug]
        language: python
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - typeguard==4.1.5
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
